Assignment 3.1
Problem Statement 1: Write a function to compute 5/0 and use try/except to catch the exceptions.

def compute_division():
    try:
        #perform divide by zero error
        div_value = 5/0
    except:
        #throw exception
        print("Error: Divide by zero")

compute_division();

#output
Error: Divide by zero
